<?php

/**
 * @file
 * nuntius_migrate.module
 */

/**
 * Implements hook_migrate_api().
 */
function nuntius_migrate_migrate_api() {
  return [
    'api' => 2,
    'groups' => [
      'nuntius_migrate' => [
        'title' => t('Import content for nuntius modules'),
      ],
    ],
    'migrations' => [
      'NuntiusMigrateTickers' => [
        'class_name' => 'NuntiusMigrateTickers',
        'group_name' => 'nuntius_migrate',
      ],
    ]
  ];
}
