<?php

/**
 * @file
 * nuntius_room.module
 */

/**
 * Implements hook_entity_info().
 */
function nuntius_room_entity_info() {
  return [
    'nuntius_room' => [
      'label' => t('Nuntius room'),
      'controller class' => 'EntityAPIController',
      'entity class' => 'nuntiusRoomEntity',
      'base table' => 'nuntius_room',
      'access callback' => 'nuntius_room_access',
      'entity keys' => [
        'id' => 'id',
        'label' => 'title',
      ],
      'entity cache' => module_exists('entitycache'),
    ],
    'nuntius_room_audience' => [
      'label' => t('Nuntius room'),
      'controller class' => 'EntityAPIController',
      'entity class' => 'nuntiusRoomAudienceEntity',
      'base table' => 'nuntius_room_audience',
      'entity keys' => [
        'id' => 'id',
      ],
      'entity cache' => module_exists('entitycache'),
    ],
  ];
}

/**
 * Entity access callback.
 */
function nuntius_room_access($op, nuntiusRoomEntity $entity, $account) {
  if (!$entity->privacy) {
    return TRUE;
  }

  // Check if the current user is the owner of the room.
  if ($entity->uid == $account->uid) {
    return TRUE;
  }

  return (bool)$entity->isAudience($account->uid);
}
