<?php

/**
 * @file
 * nuntius_room.module
 */

/**
 * Implements hook_entity_info().
 */
function nuntius_room_entity_info() {
  return [
    'nuntius_room' => [
      'label' => t('Nuntius room'),
      'controller class' => 'EntityAPIController',
      'entity class' => 'nuntiusRoomEntity',
      'base table' => 'nuntius_room',
      'entity access' => 'nuntius_entity_type_access_callback',
      'entity keys' => [
        'id' => 'id',
        'label' => 'title',
      ],
      'entity cache' => module_exists('entitycache'),
    ],
    'nuntius_room_audience' => [
      'label' => t('Nuntius room'),
      'controller class' => 'EntityAPIController',
      'entity class' => 'nuntiusRoomAudienceEntity',
      'base table' => 'nuntius_room_audience',
      'entity keys' => [
        'id' => 'id',
      ],
      'entity cache' => module_exists('entitycache'),
    ],
  ];
}
