<?php

/**
 * @file
 * nuntius_ticker.module
 */

/**
 * Implements hook_entity_info().
 */
function nuntius_ticker_entity_info() {
  return [
    'nuntius_ticker' => [
      'label' => t('nuntius ticker'),
      'controller class' => 'EntityAPIController',
      'entity class' => 'nuntiusTickerEntity',
      'base table' => 'nuntius_ticker',
      'entity access' => 'nuntius_entity_type_access_callback',
      'entity keys' => [
        'id' => 'id',
        'label' => 'title',
      ],
      'entity cache' => module_exists('entitycache'),
    ],
  ];
}
